### ISSUE TITLE
Player character wanders

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#102]
On Windows (at least) the player is unstable. It will wander around slowly. If you crouch and release the wandering will stop until you cross a chunk boundary, at which time it will resume wandering until crouch is pressed.

It also appears that, while wandering, the player will get pushed into the majority chunk (The chunk it occupies most) if standing on a boundary.

**Comment by RobotCaleb** [comment]
Further, assertions are thrown every frame when using the debug bullet libraries. The assertion appears to be on normalization attempt of a zero vector. Unsure if related to the above.

**Comment by mkfifo** [comment]
This occurs under linux as well as is captured in issue #51
