### ISSUE TITLE
glDebugMessageCallback crashes on Windows

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#103]
Looks like returning from the callback corrupts the stack. Calling convention issue? Am unable to coerce a calling convention on my callback function as it no longer fits the prototype provided by epoxy.

https://github.com/RobotCaleb/engineers-nightmare/blob/b4208b7e92b0ff14ec4cc670242df88e3c65a36f/main.cc#L427

https://github.com/RobotCaleb/engineers-nightmare/blob/b4208b7e92b0ff14ec4cc670242df88e3c65a36f/main.cc#L176

**Comment by chrisforbes** [comment]
This is fixed. We'll carry the cast hack until upstream libepoxy solves this properly.
