### ISSUE TITLE
Add sprinting to char controller?

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#113]
Hold shift? 1.5x speed or so, but can't use tools/weapons/etc.

**Comment by mkfifo** [comment]
Shift to sprint would be awesome, although I can't use it.
As a wishlist item adding a key to toggle sprint on or off :)

**Comment by chrisforbes** [comment]
I guess we want an option to choose between toggle and held.

**Comment by mkfifo** [comment]
Sorry for being difficult, and yes.

**Comment by chrisforbes** [comment]
ref #112

**Comment by chrisforbes** [comment]
Obsolete.
