### ISSUE TITLE
Add script for fetching dependencies for windows

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#121]
The manual process specified in the readme is fiddly.

**Comment by mkfifo** [comment]
I had a chat with @RobotCaleb about this the other day in irc, we have a few options:
 - script to fetch deps
 - script to fetch and build deps
 - git repo / zip file containing all deps already fetched, and script for building
 - git repo / zip file of binaries for windows land

**Comment by mikeyhc** [comment]
I like the script to fetch/build. Keeps things simple

**Comment by RobotCaleb** [comment]
That's not really simple, though. A script to build is less preferable than
a zip file containing the binaries, IMO.

cmake is non-standard and doesn't work great on Windows.

Keeping the .sln in sync isn't too much pain. There's probably a much
better way of doing it, but it's not awful once deps are setup.

To be explicit, I like zip file with headers/binaries.

**Comment by mkfifo** [comment]
I agree, I think the git repo / zip file either with the sources or with binaries is preferable to a script, as the git repo / zip is easier to maintian.

Even just creating a new git repo under the EN org. called enginers_nightmare_windows_deps with a folder per dep. (already checked out to the right version) and a README of build instructions would be a huge win.

**Comment by RobotCaleb** [comment]
:negative_squared_cross_mark: **bullet**
appears to not export anything in their dlls, so it has to be statically linked. Not sure why they even have a shared_dlls build option.

============================

:white_check_mark: **assimp**
binaries zip has unresolved externals. I generated a .def from the .dll and a .lib from the .def and it works now.

:white_check_mark: **epoxy**
works out of the box.

:white_check_mark: **freetype**
works out of the box.

:white_check_mark: **glm**
is just headers and works out of the box.

:white_check_mark: **libconfig**
built and generated .lib similar to how I did with assimp. It works.

:white_check_mark: **mman-win32**
From https://github.com/RobotCaleb/mman-win32 (to support mmap() on windows) was modified to support dll exports. Generated lib as above. Works.

:white_check_mark: **sdl2**
works out of the box.

:white_check_mark: **sdl2_image**
works out of the box.

**Comment by RobotCaleb** [comment]
Looks like we can get close. We can't just include libs as MSVC .libs are against the runtime they were built with, and can't be interchanged. I suspect a mingw build of bullet .libs might work, but I've never played with that. I'll look into getting it setup.

**Comment by RobotCaleb** [comment]
I have .a files from a mingw build, but they don't resolve externals when linked against.

We may have to have windows devs build bullet themselves.

We can add the libs that do work to a repository and add it as a submodule of this. That'll put it in the right spot. Then the instructions would be just to acquire and build a particular version of bullet

**Comment by RobotCaleb** [comment]
#154 addresses this by just packaging everything needed.

**Comment by RobotCaleb** [comment]
#157 is probably good enough to close this.
