### ISSUE TITLE
Scaffolding missing geometry

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#124]
@chrisforbes, Is the following image a regression due to #122?
(Notice that you can see through the seams between scaffolds.

![image](https://cloud.githubusercontent.com/assets/113401/7817316/691f80d0-0391-11e5-92a5-a120eb15c374.png)

**Comment by chrisforbes** [comment]
No, this looks like something else. All that patch did was alter the meshes
for the 4x4 panel and the frobnicator so they didnt have a face coinciding
with the surface they are mounted on.

Looks like there's lots of things a bit wrong with how EN is rendering on
your driver.
