### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#127]
I've told a couple of friends about EN, but can't speak much to the overall goal of the project as I only know what I've gleaned from conversation. Should someone add some of the design ideas to the readme?

**Comment by RobotCaleb** [comment]
Engineer's Nightmare (working title) is a multiplayer cooperative story-driven game where a team of players fight to keep a spaceship in working order while a DM tries to tear it apart.

Starting from scratch, or a partially pre-fabricated base, players will build a spaceship while fending off events generated by the DM. Such events might include warp core overload, or a hostile boarding party.

Centered on an engineer's point of view, Engineer's Nightmare provides a unique gameplay experience. Run miles of wiring, isolate critical systems to prevent cascading failures, expose yourself to hard vacuum. Join the Engineer's Corps today.

**Comment by RobotCaleb** [comment]
#131 adds the above to the readme.

**Comment by RobotCaleb** [comment]
Closed with this change.

**Comment by mkfifo** [comment]
+1
