### ISSUE TITLE
Sort out explicit timestep

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#142]
Currently we just assume we're going to be limited to 60Hz by vsync, and try to always be faster than that. Not going to fly.

**Comment by RobotCaleb** [comment]
#146 has a first pass at this.

Someone else should get familiar with http://gafferongames.com/game-physics/fix-your-timestep/ and set us up with a proper timestep.

**Comment by chrisforbes** [comment]
See #169
