### ISSUE TITLE
Rendering on AMD drivers is busted

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#161]
glDrawElements blows up if count is too high. When lowered, rendering looks bad.

![image](https://cloud.githubusercontent.com/assets/113401/9050666/9c65369e-3a0d-11e5-9a06-93e963cf3889.png)
![image](https://cloud.githubusercontent.com/assets/113401/9050669/9fe8b750-3a0d-11e5-9ca4-6c0383647caa.png)
![image](https://cloud.githubusercontent.com/assets/113401/9050670/a45af24e-3a0d-11e5-8cbc-7e4f24050195.png)

**Comment by RobotCaleb** [comment]
#174 addresses this. Skybox rendering is still jacked up, as well as Z issues on the sides of meshes (see the last screenshot above. Specifically on the light edges)

But we no longer crash! :feelsgood:

**Comment by chrisforbes** [comment]
I don't get the Z stepping on the sides of meshes on my 7950. Shall we open new bugs for the remaining issues?
