### ISSUE TITLE
Clang fails to link due to missing "projectile::initial_lifetime" being static

### ISSUE THREAD

**Issue by iamgreaser** [engineers-nightmare/engineers-nightmare#168]
The workaround I have is to drop the `static constexpr`, which is not the right thing to do. Line that actually causes this to be an issue (in `main.cc`):

    proj.lifetime = proj.initial_lifetime;

which is not in `struct projectile`. I have no idea how C++ is supposed to behave with a `static` variable being outside of a struct, and thanks to the sensibility and understandability of the C++ standard I have a feeling nobody else actually knows either.

A better workaround would be to declare a `const float projectile_initial_lifetime` in global scope.

A more "OO-" way of doing this would be to add a function to the struct.

**Comment by chrisforbes** [comment]
Fixed by #170
