### ISSUE TITLE
glm not list in cmake deps

### ISSUE THREAD

**Issue by mikeyhc** [engineers-nightmare/engineers-nightmare#177]
Did a build on fresh arch install, noticed that glm isn't included in cmake as a dependency.

**Comment by chrisforbes** [comment]
It doesn't have a .pc file usually. Do you want to hack up a check, or find
someone's FindGLM.cmake ?

**Comment by mikeyhc** [comment]
will put something together tonight

**Comment by chrisforbes** [comment]
Bump.
