### ISSUE TITLE
Movement lock when resetting position ('r' key) after uncrouch

### ISSUE THREAD

**Issue by PrincessRiikka** [engineers-nightmare/engineers-nightmare#196]
No problems before the first crouch or while crouching, however after releasing crouch for the first time movement is limited to one direction: the initial facing of the player. After moving in this direction there is some sort of bump (like climbing up a step, though chrisf said it was like falling down one... significant?) and then movement is back to its normal post-uncrouch non-floaty behaviour.

I've tried enabling/disabling gravity, jumping (with and without gravity), crouching more, turning, and moving; nothing seems to affect this except the initial crouch/uncrouch which does remove the floatiness but also triggers this issue.

I'm running Arch Linux on an AMD FX-8150 CPU and AMD HD7970 GPU using radeonsi from mesa 10.6.3-1 (according to pacman). glxinfo: http://pastebin.com/q55XtiKs

**Comment by chrisforbes** [comment]
This seems to be fixed. Was caused by having the character reset to a position /slightly/ penetrating the ground.
