### ISSUE TITLE
#196 can trigger massive performance loss

### ISSUE THREAD

**Issue by PrincessRiikka** [engineers-nightmare/engineers-nightmare#197]
Attempting movement in a 'blocked' direction lowers my frame rate to approximately nil as long as an appropriate key is held down. Profiling showed no clearly meaningful change in time distribution between running without triggering this issue and just sitting there holding down the frame rate.

I'm not sure what to make of this, but in case this is something the needs to be handled within EN I'll leave a ticket here.

I'm running Arch Linux on an AMD FX-8150 CPU and AMD HD7970 GPU using radeonsi from mesa 10.6.3-1 (according to pacman). glxinfo: http://pastebin.com/q55XtiKs

**Comment by RobotCaleb** [comment]
@alzeih - Here's the bug I mentioned.
Fix is likely to redo the character controller. It's pretty crazy in there.

**Comment by chrisforbes** [comment]
Still a thing.
