### ISSUE TITLE
Component system: no good way of determining if we *have* a particular component

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#199]
(and if we *dont*, then we get surprising behavior -- we end up associated with, and mangling the first component in the instance buffer.)

**Comment by RobotCaleb** [comment]
I agree with everything you said. Do you have anything in mind?

**Comment by chrisforbes** [comment]
I think something like:

```
[in component body]
bool exists(c_entity e) { return entity.find(e) != e.end(); }
```

and then we can either test in real code that can adapt, or just assert our assumptions for debug mode.

**Comment by RobotCaleb** [comment]
That works for me. At some point we may not know what components are on things.
