### ISSUE TITLE
Lights outside of bounds don't work

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#208]
In the attached screenshot, the light visible is at like 12, -41, 2.
set_light_level checks if any of x,y,z are less than 0 and bails if so.
Light doesn't get displayed.

![image](https://cloud.githubusercontent.com/assets/113401/9360994/99a0a18c-4656-11e5-874f-da35363417f8.png)

**Comment by chrisforbes** [comment]
There's a big "TODO: toroidal addressing!". This is why.
