### ISSUE TITLE
Character controller clips through walls in some cases

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#216]
Repro case:
- From the initial viewpoint, walk to the corner ahead and to your left.
- Put your back to the wall you initially faced
- Hold the 'back' movement key, and slide a bit along the wall

Expected:
- Slide along the wall consistently

Actual:
- At some points, the character clips through the wall and ends up inside.

**Comment by RobotCaleb** [comment]
Huh. I thought I had put in an issue for this. I can't find it, so I must not have. Thanks

**Comment by chrisforbes** [comment]
Obsolete. Going to replace the character controller with something completely different
