### ISSUE TITLE
Remove orphaned surfaces when removing block

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#25]

**Comment by mkfifo** [comment]
implemented naive stripping (when block is destroyed strip all surfaces) in https://github.com/engineers-nightmare/engineers-nightmare/commit/ccf07d6959d4796d16b60c07ef8d1fc56042caba

working on re-parenting surfaces to neighbouring blocks if present now

**Comment by chrisforbes** [comment]
fixed this (and adjusted for new surface-pair behavior) \o/
