### ISSUE TITLE
Wiring attachment parents don't get set

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#254]
`attach.parent` only gets incremented in rebuild. Rebuild currently never gets called.

Merging of two wire runs is therefore impossible. After adding rebuild call to attach delete branch (#253) we are able to merge two wire runs. However, they don't get fixed up to have the same parent. The wire run is connected, but contains two separate parents.

**Comment by chrisforbes** [comment]
We're just testing `a.parent == b.parent`. That's not actually good enough -- there may be a bit of path that hasn't been compressed away.

Instead, we need to test `attach_topo_find(a) == attach_topo_find(b)`

**Comment by RobotCaleb** [comment]
Will that work if rebuild is never called? I'm not seeing where parent would ever get set to anything other than what already exists except in rebuild.

**Comment by chrisforbes** [comment]
Unify sets it, and find sets it (as it compresses a path)

**Comment by chrisforbes** [comment]
I think this is resolved now? Reopen if you think it's still broken.
