### ISSUE TITLE
Add support for crouching

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#27]

**Comment by chrisforbes** [comment]
This probably needs deep mangling of the character controller

**Comment by chrisforbes** [comment]
Switch from the capsule to a same-radius sphere?

**Comment by chrisforbes** [comment]
Also, raycasts to ensure it's possible (no room to stand up -- can't stand up)

Also, interaction with jumping might be tricky.

**Comment by mkfifo** [comment]
I do like the idea of taking the current radius for width (0.35 ?) and making it the radius for the whole sphere when crouched (so crouching moves to sphere).

I also think you only be able to be fully crouching or fully standing, source games for example allow partial states (they allow you to stand as much as a space can manage) and this can lead to various problems, so raycasting to check for permission before un-crouching works nicely.

Unsure about jumping.

**Comment by chrisforbes** [comment]
Jump+crouch interaction is usually where things get weird. We can just
disallow it entirely.

**Comment by mkfifo** [comment]
@chrisforbes +1 for disallowing jumping while crouched.

**Comment by mkfifo** [comment]
This does mean we probably want to process user actions in a certain order to make sure we correctly handle the case where the user presses both jump and crouch simultaneously, always processing crouching first and then having jump check state is sufficient.

**Comment by chrisforbes** [comment]
Input plumbing done, implementation leaves quite a lot to be desired. Standup is not checked -- just instant.

Auto stair climbing on scaffold edge doesn't seem to work from outside -- more or less usable from inside though.

**Comment by chrisforbes** [comment]
deferred standup, but the checking doesn't quite work.

**Comment by chrisforbes** [comment]
\o/
