### ISSUE TITLE
Refactor tools

### ISSUE THREAD

**Issue by b414213562** [engineers-nightmare/engineers-nightmare#298]
- [ ] Put add_surface_tool declaration into add_surface.h.
- [ ] Put add_block_tool declaration into add_block.h
- [ ] Put fire_projectile_tool declaration into fire_projectile.h
- [ ] Put remove_block_tool declaration into remove_block.h
- [ ] Put remove_surface_tool declaration into remove_surface.h
- [ ] Put add_wiring_tool declaration into add_wiring_tool.h
- [ ] Put add_wiring_tool definitions into add_wiring_tool.cc

**Comment by b414213562** [comment]
I'll work on this to learn some of the codebase and clean up main.cc a bit.

**Comment by chrisforbes** [comment]
Note that you don't need the headers -- the only part of the tool exposed outside its own source file is a factory function. See how the existing tools in src/tools/ do it.

**Comment by RobotCaleb** [comment]
I think this is all wrapped up as of #431
