### ISSUE TITLE
Holes in chunk grid (theoretically) cause atmo anomalies

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#308]
If some chunks are fully contained within a sealed space, but the chunks were never touched, they won't exist. The atmo topology code assumes that nonexistent chunks are 'outside', so you won't be able to pressurize this space.

**Comment by chrisforbes** [comment]
Plan is to cause any nonexistent chunks not on the boundary of the AABB to exist.

**Comment by RobotCaleb** [comment]
Closed with #309
