### ISSUE TITLE
Fix chunk modification lag

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#311]
This is getting horrible.

**Comment by chrisforbes** [comment]
OK, I see it worse than everyone else because on one of my panels I get vsynced to a "more cinematic" 30hz. With vsync disabled, the chunk modification lag is very slight -- so we're fouling up the timing somewhere.

**Comment by RobotCaleb** [comment]
It's still pretty annoying. Now doors opening and closing trigger it.

**Comment by chrisforbes** [comment]
This is a massive problem.
