### ISSUE TITLE
placing surface must check for existing surface on neighboring block

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#33]
This becomes a problem once we have issue #28 behaving correctly

We want to avoid the situation where you have 2 adjacent blocks with both of their 'inside' faces covered in a surface, that is between any 2 adjacent blocks there can only be at most one surface.

**Comment by chrisforbes** [comment]
New invariant : both sides of a surface must be the same.

**Comment by chrisforbes** [comment]
Closing as unnecessary
