### ISSUE TITLE
Pressure calculations don't agree

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#336]
We calculate pressure in the pressure sensors, which doesn't seem to match the calculation done in tick_gas_producers.

**Comment by chrisforbes** [comment]
Is there an actual bug here? tick_gas_producers doesn't really care about pressure.

**Comment by RobotCaleb** [comment]
This may have been an anomaly due to invalid testing last night. I tested again this afternoon and it looked like they were in sync.
