### ISSUE TITLE
abstract keybinding and action logic out of main.c:handle_input

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#34]
add an enum type for possible actions

    enum actions{ ACTION_JUMP; };

add an array keyed on action (enum member) with the value being the sdl scan code

    static binding[1] = { SDL_SCANCODE_SPACE };

update controller logic to be similar to

    if (keyboard_state[binding[ACTION_JUMP]]) { jump(); }

**Comment by chrisforbes** [comment]
I've possibly screwed this up a bit while addressing #47. It might be that we need parallel binding mechanisms for various input devices.

I'm thinking of other game binding UIs, with actions listed against a column for each of keys/mouse/controller.
