### ISSUE TITLE
Consider alternative block placement schemes

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#35]
Currently we raycast to find a block, and then place a new block by following the surface normal, this is similar to how minecraft style games work and often requires some 'funky angling' (e.g. having to creep towards the edge of a block while looking 'down' at it's outer edge in order to extend a ledge).

This is of particular use when you want to place a block in a position you cannot easily point the cursor at, some quick examples being extending a ledge of placing a block on top of another (as we want to avoid having to 'jump and click')

I think there are a few alternatives that may behave better, my current favourite is dividing the surface of a block into 5 regions: one in the center, and one along each of the 4 edges. When you go to place a block the location of the block placement is determine by which of these regions your raycast hits:

hit center spot = place block along surface normal
hit z plus edge = place block in z plus direction of block
etc.

**Comment by chrisforbes** [comment]
I think that with player-controllable artificial gravity, this might end up a non-issue. Most construction done in zero-G to make it easier to move around.
