### ISSUE TITLE
integrate ship_space resizing with block placement

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#37]
AFAIK this will only be useable once both #28  and #29 are in place

We want it such that when the user places a block that would be outside the ship space, that the placement tool controller calls an appropriate ship_space::resize(x,y,z)

Note that a resize preserves all existing chunk co-ords but does not instantiate any new co-ords (ship_space is sparse by default), it is up to the caller to instantiate the desired new chunk(s).

**Comment by mkfifo** [comment]
Just realised this is doable once either #28 or #29 are in place

**Comment by chrisforbes** [comment]
resize currently only works in positive directions

**Comment by chrisforbes** [comment]
note that surface placement now sometimes requires a chunk to be created, so that storage exists for the reverse side of the surface.

**Comment by mkfifo** [comment]
ship_space now has a new `ensure(block_x, block_y, block_z)` interface that will resize if needed and instantiate any needed chunks.

I have just pushed a fix that allows this to work with negatives as well.

Integrating with the tools now.

**Comment by chrisforbes** [comment]
\o/

**Comment by mkfifo** [comment]
awesome!
