### ISSUE TITLE
mat_rotate_mesh doesn't behave properly

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#374]
@chrisforbes Can you explain what needs to be done to fix?

Also, when it's fixed up, we need to fix mat_block_face.

**Comment by chrisforbes** [comment]
Right, for attaches it didn't matter which axis we chose as long as it
wasn't too close to the normal. For this, we want to prefer +z.

**Comment by chrisforbes** [comment]
I'll fix it (a bit later when my stream goes on again)

**Comment by chrisforbes** [comment]
Fixed
