### ISSUE TITLE
Add tool for configuring reader components

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#379]
We need to be able to configure the ent matching, message type matching, and someday logic op in the reader components. A first pass might look like:
- Primary use: select entity to configure
- Secondary use: set filter to highlighted entity
- Cycle mode: select next reader_component instance on entity (requires that we do multi instance support)

**Comment by RobotCaleb** [comment]
is this a duplicate of #117?

**Comment by RobotCaleb** [comment]
Cycle mode refers to #380
