### ISSUE TITLE
Add action descriptions for keybinding UI.

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#38]
This work is based on the `enum actions` described in #34 

For UI purposes we will want to be able to convert a value of the action enum into a description string, a simple array indexed by action members should suffice

    // FIXME actions is a terrible name...
    enum actions {
        ACTION_JUMP;
        TOOL_PLACE_SCAFFOLD;
    };

    static char *action_desc[] = {
        "jump",
        "a tool for placing scaffolding blocks"
    };

so that we can then display this text to the user

    printf("%s\n", action_desc[TOOL_PLACE_SCAFFOLD]);

**Comment by chrisforbes** [comment]
tool descriptions are kindof done now

**Comment by chrisforbes** [comment]
only the actions map really matters for this -- the tool stuff is all going to depend on what the player has placed in which slots anyway

**Comment by chrisforbes** [comment]
@RobotCaleb do you want to figure out what if anything is still useful from this ticket?
