### ISSUE TITLE
Component manager needs support for multiple components with same c_entity

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#380]
We need some way of navigating these nodes. I think we store an index into the pool for next and previous. We want circular-linked so that we don't have to care about finding the first when iterating.

Does this mean all of our components in gen need to look like:
float,intensity
float,requested_intensity
unsigned,next
unsigned,prev

Or should we have component gen create this for us? Are multiple of same components on entity the rule or an exception?

**Comment by chrisforbes** [comment]
Not doubly linked, circular.

**Comment by RobotCaleb** [comment]
Yes, my bad. Fixed.

**Comment by chrisforbes** [comment]
I think if the component contains unsigned 'next', then the generator should set this up for us.

**Comment by RobotCaleb** [comment]
Do we care about prev?

**Comment by chrisforbes** [comment]
Not sure we care about this any more if we have subentities.
