### ISSUE TITLE
UI: Proper UI system

### ISSUE THREAD

**Issue by RobotCaleb** [engineers-nightmare/engineers-nightmare#381]
We need a proper UI system. Buttons, scrollable panels, text entry, etc.

Presumably this is a third party library.

Previous discussions have mentioned immediate mode GUI systems and full canned libraries.

**Comment by Unit158** [comment]
CEGUI is pretty neat. Worth a glance.

**Comment by chrisforbes** [comment]
Evaluating Dear Imgui for this.
