### ISSUE TITLE
Tidy up VS solution -- get rid of broken 32bit build etc.

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#409]
Possibly just nuke the whole thing and use cmake on windows?

**Comment by RobotCaleb** [comment]
32 bit build has been removed in #419 

cmake is still an option, but needs care to do properly.

**Comment by chrisforbes** [comment]
Closing for now. 32bit is gone; converting windows build to cmake is a pile of effort that could be better spent on gameplay stuff.
