### ISSUE TITLE
Do mesh swaps rather than material swaps for surfaces

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#418]
Material index that comes along for the ride should just be the material that is correct for that mesh, not something we actively drive.

**Comment by chrisforbes** [comment]
This is getting very close to doable... do you need a second set of surface meshes to make it happen?

**Comment by RobotCaleb** [comment]
I'm not sure. What are you seeing that I'm missing?

**Comment by RobotCaleb** [comment]
Oh, I see. I thought we had grate and glass meshes already
