### ISSUE TITLE
Doors: fix missing attachments

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#427]
Currently doors are uncontrollable and unpowerable because they lack attachment points.

**Comment by chrisforbes** [comment]
Moving back to MV .obj world we can't do the attachment dummy objects any more -- and they don't fit the new wiring model. Just mark which wiring types the entity accepts on the entity stub.

**Comment by RobotCaleb** [comment]
This will be closed by #454
