### ISSUE TITLE
Don't generate so much junk structure outside the ship

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#450]
Framing mesh is pretty heavy; we should avoid generating so much of it. Ideally, we'd also generate a complete outer hull.

Idea for doing this: initially mark every cell as 'never touched'. When making a room (including the initial room) convert any 'never touched' on the outer shell of the room to framing.

**Comment by RobotCaleb** [comment]
Is this finished with #453
