### ISSUE TITLE
fix mock ship space to have surfaces on the outside too

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#48]

**Comment by chrisforbes** [comment]
currently we have a bunch of hackery in the tools to cope with the surface invariants being broken. it would be good to be able to throw that away.

**Comment by chrisforbes** [comment]
This thing is yours.

**Comment by mkfifo** [comment]
Please note that I haven't put a roof on our mock ship space, so at z == 7 the scaffolding blocks still lack a face on their surface_zp

**Comment by chrisforbes** [comment]
Description was a bit rubbish -- the actual issue is the back side of the surfaces is not present. Reopening.

**Comment by mkfifo** [comment]
hahaaaahha

**Comment by mkfifo** [comment]
I will get on to that tonight then

**Comment by mkfifo** [comment]
ugly fix, but should only be temporary (famous last words).
