### ISSUE TITLE
replace dynamic_grid<T> with an implementation on top of unordered_map<T>

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#56]
This requires that we implement a specialization of std::hash<T> for the position (ivec3?) type.

**Comment by chrisforbes** [comment]
this thing has been just a rat's nest of bugs.

**Comment by mkfifo** [comment]
I didn't see the rat's nest coming, the offset (allowing negative co-ords) made the whole thing too messy.

I started the work last night removing dynamic_grid<chunk*> to replace it with unordered_map<ivec3, chunk*>

Haven't started on the hash function.

**Comment by mkfifo** [comment]
Fixed in 369b474abbae8bece6c3e5eba8d1fff468923763
