### ISSUE TITLE
Fix raycast results being weird in negative space

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#60]
We appear to be off by one somewhere in here.

**Comment by mkfifo** [comment]
This appears to be a bias towards 0 along the negative axis.

If I toggle off gravity (G), turn 90 degrees right form spawn and fly out the double height door I am moving in the direction of -Y

if I build out in that direction (so I am building along the -Y) then all is fine

However if I then build at a right angle to this I see the bias, when building at a right angle there is a noticeable bias towards 0 (of one block) along the axis that is negative.

**Comment by mkfifo** [comment]
so if I build 6 blocks out and then move around so I am at 0, -6, 1 looking at my -6 block and along the positive X

I initiate a raycast and I see

0, -6, 1
1, -6, 1
2, -6, 1 HIT non scaffold

I then hit the e key to place and I see a block placed at
1, -5, 1

this SHOULD be
1, -6, 1
