### ISSUE TITLE
allow save and load of ship spaces

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#64]
a simple key for save and another for load, both bound to a hardcoded relative path.

**Comment by chrisforbes** [comment]
this needs a bit of thought to ensure that we can still load an older ship_space as the game evolves.

**Comment by mkfifo** [comment]
@chrisforbes yes, as a worst case I am happy to write some perl script's to massage from older->newer if needed.

**Comment by chrisforbes** [comment]
That habit of stray apostrophes isn't going to serve you well writing perl
;)

**Comment by mkfifo** [comment]
I.. I... cannot even begin to try explain how that happened...

**Comment by mkfifo** [comment]
I have started work on this in branch serialization

**Comment by mkfifo** [comment]
first attempts at block and chunk (sans entities) are 'done'
ship space still to come.
