### ISSUE TITLE
integrate OpenAL for sound

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#66]

**Comment by doctorlard** [comment]
We need to bin alut* in favour of libvorbis → PCM buffers.

**Comment by chrisforbes** [comment]
Apparently I misspoke, you can decompress a chunk at a time using
libvorbisfile, don't have to use the full api

**Comment by doctorlard** [comment]
I'd like to have a crack at this over Christmas.

**Comment by RobotCaleb** [comment]
Speak with @Pepe73 
He's tackling this right now.
