### ISSUE TITLE
consider moving to wercker for automated testing

### ISSUE THREAD

**Issue by mkfifo** [engineers-nightmare/engineers-nightmare#74]
So far travis has been nothing but pain for us since it is stuck in the past (ubuntu 12.04 lts)
as an example see issue #72 

Wercker is an interesting docker based alternative that should allow us to escape the shackles of 2012.

https://hacks.mozilla.org/2013/02/wercker-continuous-delivery-made-easy-a-webfwd-project/

http://wercker.com/

**Comment by mkfifo** [comment]
Assigning as low priority as this is currently a non-issue as all known travis ci issues have been worked around.

**Comment by chrisforbes** [comment]
I'd be inclined to just close it unless there's something further actionable. We've considered it. We might consider it again.

**Comment by mkfifo** [comment]
Fair.
